### PR TITLE
Update to use proj 0.23.1, using libproj 8.1.0

### PR DESCRIPTION
**Pull request by urschrei**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
Hmmmm missing `cmake` in the base images?

**Comment by michaelkirk** [comment]
> Hmmmm missing cmake in the base images?

The geo-ci dockerfile copies the proj installation from libproj-builder:

https://github.com/georust/docker-images/blob/master/rust-1.53/geo-ci.Dockerfile#L29

So if it's trying to build proj, something has gone wrong.

**Comment by michaelkirk** [comment]
One thought are you sure that you'd built and tagged the latest libproj-builder:rust-1.53 (with proj 8) before rebuilding and tagging the geo-ci:rust-1.53 container?

...I have no idea how to audit this =(

I'll try to reproduce it locally.

**Comment by urschrei** [comment]
I _thought_ I had…

**Comment by michaelkirk** [comment]
```
--- stderr
  feature flags specified source build  👀 👀 👀 👀 
  building libproj from source
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
```

That stderr line is from:
```
16 #[cfg(not(feature = "nobuild"))]
 17 fn main() -> Result<(), Box<dyn std::error::Error>> {
 18     let include_path = if cfg!(feature = "bundled_proj") { ‣include_path: PathBuf
 19         eprintln!("feature flags specified source build");
 20         build_from_source()?                                   
 21     } else {   
```

I wonder why we're triggering that?

**Comment by michaelkirk** [comment]
Oh, I guess I didn't realize (or maybe forgot) that using proj-network will build the bundled_proj:

enabled geo --features "proj-network" enables proj/network

geo/Cargo.toml
```
proj-network = ["use-proj", "proj/network"]
```

proj/Cargo.toml
```
network = ["bundled_proj_tiff", "reqwest"]
```
and
```
bundled_proj_tiff = [ "proj-sys/bundled_proj_tiff" ]
```

proj-sys/Cargo.toml
```
bundled_proj_tiff = ["bundled_proj"]
```

So I guess this is intended. I'm not sure why this was added - I guess maybe it's hard to probe whether the existing proj installation has the tiff feature? 

Maybe in the immediate, the thing to do is simply to install cmake on geo-ci, as @urschrei suggested long ago. 😬

**Comment by urschrei** [comment]
It's the easier option for now, for sure.

**Comment by michaelkirk** [comment]
BTW, I do go to add `cmake` to the geo-ci base docker image, but then the build failed because it needed sqlite... and presumably all the other proj deps.

Ultimately I'd be OK with having just one heavy base docker image for ci, it's no big deal. 

But the primary reason it gives me pause was because now I'm wondering if we'd be newly requiring `geo` users to  have to build proj from source even if they already have a compatible version installation installed. 

For example, a (very) cursory look shows that [debian (sid)](https://packages.debian.org/sid/libproj-dev) and [macos homebrew](https://formulae.brew.sh/formula/proj) include libtiff. It seems likes those users shouldn't need to build libproj from source if we get things set up nicely.

**Comment by urschrei** [comment]
Let's see if this will merge even though cargo-tarpaulin is failing with an error

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
OK! But will the merge commit skip the coverage check 🧐?

**Comment by urschrei** [comment]
OK, now what? Manual merge?

**Comment by michaelkirk** [comment]
In the immediate, I'm totally fine with a manual merge. I'm going to open a separate issue about tarpaulin.

**Pull request merged**
