### PR TITLE
Add rstar MultiPolygon compat

### PR DESCRIPTION
**Pull request by urschrei**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

This should merge before #1246

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]

**Comment by urschrei** [comment]
Now what

**Review by michaelkirk — APPROVED** [review]

**Comment by urschrei** [comment]
Still seeing the concave hull test failure in the merge queue

**Comment by urschrei** [comment]
The concave hull algorithm uses an rtree, and we bumped rstar yesterday with some bug fixes. But why is the test passing here and failing in the merge queue?

**Comment by frewsxcv** [comment]
Can anyone reproduce it locally?

**Comment by urschrei** [comment]
Yep just managed to reproduce it on HEAD in `main`: ab9856f4.

**Comment by urschrei** [comment]
Yeah it's the rstar patch version: https://github.com/georust/rstar/blob/master/rstar/CHANGELOG.md

Not immediately obvious what change is causing this though.

**Comment by michaelkirk** [comment]
I'm putting my notes about the CI failure in a dedicated issue: https://github.com/georust/geo/issues/1260

**Pull request merged**
