### PR TITLE
Fix polygon distance fast path

### PR DESCRIPTION
**Pull request by urschrei**
This replaces the previous, buggy iteration logic: we now rely upon the fact that this is a linear algorithm (thank you for the inspiration for the fix @msalib) so the minimum distance can be calculated by spinning the calipers at most n times, where n is the <s>number of edges in the larger of the two polygons</s> total number of vertices in both polygons' exteriors.

Other improvements include re-calculating the slope according to the same logic in the original algorithm, fixing a branching difference in our port, and new tests that cover both the original and minimised errors that were found.

# THAT HAVING BEEN SAID:

This algorithm's implementation is **extremely** magical and if it were proposed for addition today I would be dubious about its inclusion: why does the `100.00` value work in various functions, but `float::max_value()` doesn't? Why is the epsilon (`0.002`) comparatively large, and why does substituting `float::min_value()` not work? Nobody knows.

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by urschrei** [comment]
See #555 for previous discussion.

**Comment by urschrei** [comment]
Bors try

**Comment by urschrei** [comment]
Oops, need to fix num iterations to be n + m where n = poly1.exterior().points().len() and m = poly2.exterior().points().len().

See https://escholarship.mcgill.ca/downloads/3x816p60j?locale=en pp30-32

**Comment by rzru** [comment]
@urschrei hi! looks like this is still broken in main branch. I wonder maybe this bugfix was lost during moving from master => main?

**Comment by urschrei** [comment]
No, the bugfix and test that originally reproduced it are in `main`: [`here`](https://github.com/georust/geo/blob/main/geo/src/algorithm/euclidean_distance.rs#L1034-L1068). Do you have a failing test you can show me?

**Comment by rzru** [comment]
@urschrei sure thing 

```rust
    #[test]
    fn test_2_polygons_stucks_forever() {
        let first_polygon = Polygon::new(
            LineString::new(vec![
                Coordinate::from((57.39453770777941, 307.60533608924663)),
                Coordinate::from((67.1800355576469, 309.6654408997451)),
                Coordinate::from((84.89693692793338, 225.5101593908847)),
                Coordinate::from((75.1114390780659, 223.45005458038628)),
                Coordinate::from((57.39453770777941, 307.60533608924663)),
            ]),
            vec![],
        );
        let second_polygon = Polygon::new(
            LineString::new(vec![
                Coordinate::from((138.11769866645008, -45.75134112915392)),
                Coordinate::from((130.50230476949187, -39.270154833870336)),
                Coordinate::from((184.94426964987397, 24.699153900578573)),
                Coordinate::from((192.55966354683218, 18.217967605294987)),
                Coordinate::from((138.11769866645008, -45.75134112915392)),
            ]),
            vec![],
        );

        assert_relative_eq!(first_polygon.euclidean_distance(&second_polygon), 0.0)
    }
```

this test should fail, distance is obvious not 0.0, however it just stucks forever

**Comment by urschrei** [comment]
Reverting to the initial fix causes this test to pass. Urgh.

**Comment by urschrei** [comment]
Hi @rzru, the fix will merge to `main` today – thanks for reporting and providing a test!

**Comment by rzru** [comment]
hey @urschrei, thank you for your fast support and this amazing library!

**Pull request merged**
