### PR TITLE
Adding tarpaulin with coveralls to CI pipeline

### LINKED ISSUE #274: Use tarpaulin + coveralls for coverage
https://github.com/xd009642/tarpaulin works well for line coverage now, and has workspace + feature support.

### PR DESCRIPTION
**Pull request by griffobeid**
Closes #274 

Hello everyone! :wave: 

With this PR I am adding tarpaulin with coveralls coverage reporting to the CI pipeline. Not sure if this project already has coveralls setup, or Travis Pro?

I found these instructions on [coveralls.io](coveralls.io)
Screenshot from 2019-08-24 15-17-00

## Implementation
This is basically straight from the tarpaulin readme https://github.com/xd009642/tarpaulin#travis-ci-and-coverage-sites

## Usage
To use tarpaulin locally you need to install it with cargo.
```
cargo install cargo-tarpaulin
```

Now you can run tarpaulin.
```
cargo tarpaulin -v
```

## Coverage Report
* 89.01% coverage
* 4724/5307 lines covered
Peek 2019-08-24 15-36

### CODE REVIEW

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
LGTM! I switched on coveralls, first report is [here](https://coveralls.io/builds/25331806).  
We should probably gate the tarpaulin run on a single feature set, since it massively increases the build time (from ~3 mins per run to ~23 mins per run, x 7), and add the coveralls badge to the README.

**Comment by griffobeid** [comment]
For sure, any particular feature set we should gate this on? Maybe one GEO_TYPES and one GEO?

**Comment by griffobeid** [comment]
I gated on one feature and added the badge to the README, so I think this is good to go!

**Pull request merged**
