### PR TITLE
Add +=, -=, *=, and /= for Point

### PR DESCRIPTION
**Pull request by willhansen**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Related issue: https://github.com/georust/geo/issues/713

### CODE REVIEW

**Comment by michaelkirk** [comment]
LGTM, thanks @willhansen! 

I'm going to wait a couple more days before merging in case anyone else wants to weigh in.

bors try

**Comment by michaelkirk** [comment]
Seems like legitimate failures in the new tests - please update.

Take a look at our [ci workflow](https://github.com/georust/geo/blob/master/.github/workflows/test.yml#L51) for hints at what tests you should be running.

**Comment by willhansen** [comment]
I was running the wrong test command locally.  Should be fixed now.

**Comment by michaelkirk** [comment]
bors retry

**Pull request merged**
