### PR TITLE
Add From<Line> for LineString #625

### PR DESCRIPTION
**Pull request by NolwennD**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Hello,

Here a small patch for #625, I hope it’s good enough.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

**Review by michaelkirk — COMMENTED** [review]
This looks good! Could you add a new entry to geo-types/CHANGES.md?

**Comment by NolwennD** [comment]
I have updated the changelog.

**Review by michaelkirk — APPROVED** [review]
bors r+

Thank you!

**Comment by michaelkirk** [comment]
> Build failed:

Looks like crates.io is having a fit. We'll try again later.
```
Run cargo install cargo-all-features
Updating crates.io index
Downloading crates ...
Downloaded cargo-all-features v1.5.0
Installing cargo-all-features v1.5.0
Downloading crates ...
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/termcolor/1.1.2/download`, got 503
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/termcolor/1.1.2/download`, got 503
error: failed to compile `cargo-all-features v1.5.0`, intermediate artifacts can be found at `/tmp/cargo-installRvlbhA`
```

**Comment by michaelkirk** [comment]
bors retry

**Pull request merged**
