### PR TITLE
Breaking change, rust v1.59 is not longer supported, simplify

### PR DESCRIPTION
**Pull request by martinfrances107**
By Simplify I mean replace  the "use_rstat_0_8" and "use_rstat_0_9" with a single  "use_rstar".  The namedspace-features issue in no longer relevant.

### CODE REVIEW

**Comment by martinfrances107** [comment]
Opps I have just seen a problem, I need to update the change log

my bad. one sec.

**Comment by lnicola** [comment]
As mentioned in https://github.com/georust/geo/issues/965#issuecomment-1382159152, this involves a breaking change to `geo-types`. We'll do it at some point (when?), but I think we'll want to keep supporting the one old version of `rstar` (0.9 when 0.10 comes out) until it reaches 1.0. This is in line with other popular crates like https://docs.rs/postgres/latest/postgres/#features.

**Comment by martinfrances107** [comment]
understood, I will make changes tomorrow.

**Comment by martinfrances107** [comment]
This issue has been fixed elsewhere

**Pull request closed without merging**
