### PR TITLE
Prepare for geo 0.26 / geo-types 0.7.11 releases

### PR DESCRIPTION
**Pull request by urschrei**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
Ship at will! 

(and push up tags for geo-0.26.0 and geo-types-0.7.11 😉)

**Comment by urschrei** [comment]
Yes I just merged this PR _without_ bumping the Cargo version numbers, why do you ask?

**Comment by urschrei** [comment]
OK, I'm just going to push the updated Cargos straight to `main` and tag that commit.

**Comment by michaelkirk** [comment]
SGTM

**Pull request merged**
