### PR TITLE
add rust-1.51 to ci

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Depends on https://github.com/georust/docker-images/pull/12

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]

**Comment by lnicola** [comment]
1.52 is already out, but does it make sense to test on every version?

**Comment by michaelkirk** [comment]
> 1.52 is already out, but does it make sense to test on every version? stable and some MSRV (and maybe beta or nightly) should suffice.

Yes! I think ideally we'd do something like what you've described, where we target tags like "stable" an MSRV (and maybe beta/nightly).

But I think that implies some machinery to automatically rebuild stable/beta/nightly, is that what you mean @lnicola? 

I'm not very familiar with docker/docker-hub, or what the best way to do something like that is, so we've just been hobbling along with manual updates so as not to get toooo far behind.

I'd be happy if you have any advice (or better yet, if you are interested in setting it up).

**Comment by lnicola** [comment]
No, I don't really have any advice about rebuilding the images automatically (though it should be scriptable, at least), but that's independent of whether we want N (=3 currently) Rust versions in the testing matrix.

**Comment by lnicola** [comment]
PS: I think GitHub Actions can be triggered on a schedule, so one approach would be to rebuild the stable/beta/nightly images daily and push them to Docker Hub.

**Comment by michaelkirk** [comment]
bors r=frewsxcv

**Pull request merged**
