### PR TITLE
introduce build matrix for rust-1.49 and rust-1.50

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Based on https://github.com/georust/docker-images/pull/11

### CODE REVIEW

**Comment by michaelkirk** [comment]
bors try

**Review by frewsxcv — APPROVED** [review]

**Comment by michaelkirk** [comment]
bors r=frewsxcv

**Comment by michaelkirk** [comment]
bors r-

I think I need to wrestle with the bors.toml due to the changes to ci

**Comment by michaelkirk** [comment]
bors try

**Comment by michaelkirk** [comment]
bors r+

FYI, I'm sneaking in another commit to organize the CI jobs under a meta job, which makes bors integration easier.

Screen Shot 2021-02-22 at 3 48 11 PM

Otherwise I *think* we'd need an entry for each `(rust version, job)` pair.

**Pull request merged**
