### PR TITLE
Polygon::interiors_push - Add an interior to the current list

### PR DESCRIPTION
**Pull request by rory**
For a project, I am slowly creating polygons, and I needed a way to add an interior ring to a polygon, so I added `Polygon::interiors_push`.

I couldn't see how to do it with `Polygon::interiors_mut`.

### CODE REVIEW

**Comment by rory** [comment]
The rust-geo-booleanop library probably needs this functionality too:

https://github.com/21re/rust-geo-booleanop/blob/0776c7f4e27d3d60adad92cbdeaf6340b82e3360/lib/src/boolean/connect_edges.rs#L117

**Comment by antoine-de** [comment]
Great catch, we [need](https://github.com/QwantResearch/osm_boundaries_utils_rs/blob/master/src/boundaries.rs#L125) this functionality too.

**Comment by antoine-de** [comment]
great, thanks @frewsxcv !

**Pull request merged**
