### PR TITLE
Use latest Docker images (max 1.79)

### PR DESCRIPTION
**Pull request by urschrei**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by urschrei** [comment]
NB: I had to add an "allow dead code" exception to our Sweep-line impl to allow the lint to pass as it became more strict at some point post Rust 1.75, so happy to add a Changelog entry for this PR if need be.

**Comment by michaelkirk** [comment]
I think we should keep the MSRV in Cargo.toml synced with whatever we're running on CI.

And then I'd say bumping MSRV deserves a change log entry.

**Comment by urschrei** [comment]
> I think we should keep the MSRV in Cargo.toml synced with whatever we're running on CI.
> 
> And then I'd say bumping MSRV deserves a change log entry.

Done (and thanks for fortuitously updating the Docker images yesterday!)

**Comment by michaelkirk** [comment]
It was no coincidence! Thanks for finishing the job.

**Review by michaelkirk — APPROVED** [review]
I pushed up another commit to bump `rust-version` in Cargo.toml.

**Comment by urschrei** [comment]
Ah, I just…didn't commit my Cargo changes. Very good.

**Pull request merged**
