### PR TITLE
Remove cargo-tarpaulin due to instability

### PR DESCRIPTION
**Pull request by urschrei**
See discussion at #676

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
This LGTM, but maybe leave it open for a bit in case others have input?

**Comment by urschrei** [comment]
@frewsxcv and @lnicola WDYT?
@rmanoka I saw a 👍 from you yesterday…

**Review by lnicola — APPROVED** [review]
Tarpaulin is nice, but finicky like this. I don't think keeping it is worth the hassle.

**Comment by rmanoka** [comment]
Yes, I agree about removing tarpaulin.  I could never get it running locally, so I also never found it super robust.

**Review by frewsxcv — APPROVED** [review]

**Comment by urschrei** [comment]
Bors r+

**Pull request merged**
