### PR TITLE
Update fmt and clippy for Rust 1.83

### PR DESCRIPTION
**Pull request by kylebarron**
- [ ] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by kylebarron** [comment]
Does the failing test imply that the fmt of rust 1.83 is not a superset of the fmt of rust 1.79? Should we update that CI to use rust 1.83?

**Comment by michaelkirk** [comment]
I'd be fine to update the format version in CI.

**Comment by kylebarron** [comment]
Ah looks like we need to push a new container. That's in https://github.com/georust/docker-images?

**Comment by michaelkirk** [comment]
> Ah looks like we need to push a new container. That's in https://github.com/georust/docker-images?

Ah yes, I'm taking a look at that now.

**Review by michaelkirk — APPROVED** [review]

**Pull request merged**
