### PR TITLE
Add missing implementations for `Intersects`

### PR DESCRIPTION
**Pull request by msalib**
See #724 

- [X] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by msalib** [comment]
Feel free to ditch the giant generated test case; I just wanted something super simple to check completeness.

**Review by michaelkirk — APPROVED** [review]
Thanks! 

bors r+

**Comment by michaelkirk** [comment]
CI failure seems unrelated to your change, and instead due to a dependency that bumped their MSRV.

I'm working on figuring out what our new MSRV would be with the latest "arbitrary" crate.

**Comment by lnicola** [comment]
We could also pin `arbitrary` to `1.0`.

**Comment by michaelkirk** [comment]
bors retry

**Comment by michaelkirk** [comment]
bors retry

**Pull request closed without merging**
