### PR TITLE
Prepare for 0.27.0 release

### PR DESCRIPTION
**Pull request by frewsxcv**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by michaelkirk** [comment]
There are also some unreleased geo-types changes that I think needs to be released first, and then geo needs to bump its geo-types dependency. 

(I'm happy to see them both released)

**Comment by michaelkirk** [comment]
I've opened a PR for the geo-types release here: https://github.com/georust/geo/pull/1110

**Comment by michaelkirk** [comment]
I [released geo-types 0.7.12](https://github.com/georust/geo/releases/tag/geo-types-0.7.12) and took the liberty of rebasing this branch and updating `geo`'s `geo-types` dependency. 

(LMK if you'd prefer me to not clobber your PR's in the future @frewsxcv, I surmised you are eager for a release so I'm trying to be efficient. )

**Review by michaelkirk — APPROVED** [review]

**Comment by frewsxcv** [comment]
Thank you @michaelkirk! Forgot to check if this depended on anything new geo-types

**Pull request merged**
