### PR TITLE
Restore convex hull tests

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Supersedes #912 which had two goals:

**goal 1:** Run our existing tests, some of which we were accidentally skipping.

**goal 2:** added a new test to demonstrate a presumed bug, but this test was based on incorrect assumptions.

I've taken away the test from goal 2, so that this PR is now only about making sure we're running our existing tests.

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
lgtm with merge conflicts fixed

**Comment by michaelkirk** [comment]
bors r=frewsxcvc

**Comment by frewsxcv** [comment]
Screen Shot 2022-11-23 at 2 34 40 PM

**Comment by michaelkirk** [comment]
I suppose it's no good fixing a typo in a bot command. I'm sorry nonetheless.

**Pull request merged**
