### PR TITLE
issue #1084: panics on haversine_closest_point

### PR DESCRIPTION
**Pull request by fegies**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
Issue #1084:
- added failing test case reproducing problem
- Fixed the issue

### CODE REVIEW

**Review by urschrei — APPROVED** [review]
I'm happy with this, my one minor comment notwithstanding.

**Comment by urschrei** [comment]
(The Clippy complaint is also trivial)

**Comment by urschrei** [comment]
Thanks! And if you could also add an entry to `geo/CHANGES.md` (apologies, I should have asked yesterday)

**Comment by fegies** [comment]
> Thanks! And if you could also add an entry to `geo/CHANGES.md` (apologies, I should have asked yesterday)

To a patch subversion? 0.27.1?

**Comment by urschrei** [comment]
> > Thanks! And if you could also add an entry to `geo/CHANGES.md` (apologies, I should have asked yesterday)
> 
> 
> 
> To a patch subversion? 0.27.1?
> 
> Or add the Unreleased Header?
> 
> 

Just under Unreleased please!

**Comment by fegies** [comment]
Done.

**Comment by urschrei** [comment]
Thanks, I'll leave it open for another few hours in case anyone else wants to weigh in.

**Pull request merged**
