### PR TITLE
geo/geo bump  proj to 0.27.0

### PR DESCRIPTION
**Pull request by martinfrances107**
The is a ongoing discussion in #856 about how to signal to the wider community that our dependencies are changing.

But this is issue follows the pattern developed in #850

### CODE REVIEW

**Comment by michaelkirk** [comment]
This LGTM, but I'm *also* not very concerned about publishing a breaking release for geo. I'd also be fine to just strictly bump proj without the range.

My position on this is different with geo-types - which is used across a lot of other crates. I'm much more willing to put effort into *not* breaking geo-types.

I'll wait until tomorrow to merge in case anyone else wants to weigh in.

**Comment by martinfrances107** [comment]
> I'd also be fine to just strictly bump proj without the range.

Great that is my preference..fixed.

**Comment by michaelkirk** [comment]
bors retry

I pushed up a new commit to your branch to adapt to the latest proj.

**Pull request merged**
