### PR TITLE
Prepare for geo-types 0.7.4 release.

### PR DESCRIPTION
**Pull request by frewsxcv**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

As per https://github.com/georust/geo/pull/772#issuecomment-1089513399

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]

**Comment by michaelkirk** [comment]
Probably good to get a release out anyway! 

But just in case you missed it, it's no longer blocking #742 (solved via patching shown in #795)

**Comment by frewsxcv** [comment]
I didn't see! I'll still plan on merging and releasing since I already opened this

**Comment by frewsxcv** [comment]
bors r=nyruik,michaelkirk

**Pull request merged**
