### PR TITLE
No std

### LINKED ISSUE #422: support no_std
I'd like to use geo in a `no_std` build. Any chance this will be supported soon? If not on you roadmap, would you accept a PR?

### PR DESCRIPTION
**Pull request by brenzi**
fixes #422 

builds with rust stable.
must patch rstar dependency until upstream PR gets merged: https://github.com/Stoeoef/rstar/pull/27

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks for doing this work @brenzi. Unfortunately we're still blocked on the rstar no-std PR so we can't merge. In the meantime, I'm going to close this, but we can reopen and merge once rstar becomes no-std compatible

**Comment by wucke13** [comment]
@brenzi rstar has now support for `no_std`. Do you have any interest in bringing this forward soonish?

**Comment by frewsxcv** [comment]
If a PR is opened with `no_std` support with the latest `rstar` version, I'm happy to review it!

**Comment by wucke13** [comment]
@frewsxcv I think I can rebase this if @brenzi doesn't do it. However, with remark to my [other comment](https://github.com/georust/geo/issues/422#issuecomment-1021327241), there still remains a strategic question: Are we fine to have two configurations of `geo` available, one with `no_std` support and `alloc` allowing everything one can do now, and one with `no_std` support but without `alloc`, containing only those algorithms and types which do not depend on heap memory?

**Pull request closed without merging**
